/**
 * products.ts — Antocarz
 * Catálogo de productos con subcategorías, código y precio numérico.
 * Principio Information Expert: único módulo que conoce el catálogo completo.
 */

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  code: string;
  price: number;
  priceFormatted: string;
  description: string;
  image: string;
  features: string[];
  compatible: string[];
  badge?: string;
}

export const BRANDS = ['JBL', 'Pioneer', 'Hawk', 'BRM', 'Genérica'] as const;

export const CATEGORIES_TREE: Record<string, string[]> = {
  'Car Audio':            ['Radios', 'Parlantes', 'Subwoofer', 'Adaptador Bisel', 'Arnés Cables'],
  'Seguridad':            ['Alarmas', 'Alzavidrios', 'Bloqueos de Motor', 'Cierre Centralizado', 'Control de Flotas', 'GPS Rastreador', 'Sensores de Reversa', 'Otros Seguridad'],
  'Polarizado Americano': ['Polarizado Camionetas', 'Polarizado Hatchback', 'Polarizado Sedan', 'Polarizado SUV'],
  'Láminas de Seguridad': ['Láminas Camioneta', 'Láminas Camioneta SUV', 'Láminas Hatchback', 'Láminas Sedan', 'Otros'],
  'Iluminación LED':      ['Feeston', 'Neblineros', 'T10', 'TURBO LED'],
  'Aire Acondicionado':   ['Carga de A/C', 'Carga de Aceite Compresor', 'Filtro de Polen', 'Otros A/C'],
  'Insumos Eléctricos':   ['Ampolletas'],
  'Equipamiento':         ['Lonas Marítimas'],
  'Mantenimiento':        [],
  'VINILO':               [],
};

export const CATEGORIES = Object.keys(CATEGORIES_TREE);
export const MAX_PRICE = 325000;

export const PRODUCTS: Product[] = [

  // ── CAR AUDIO — RADIOS ────────────────────────────────────────────────────
  {
    id: 'radio-android-jbl-10',
    name: 'Radio Android JBL 10"',
    brand: 'JBL',
    category: 'Car Audio',
    subcategory: 'Radios',
    code: 'ANT-CA-001',
    price: 189990,
    priceFormatted: '$189.990',
    description: 'Radio multimedia con pantalla táctil HD de 10 pulgadas. Sistema Android con acceso a todas las apps, GPS integrado, WiFi, Bluetooth 5.0 y compatibilidad con CarPlay y Android Auto.',
    image: '/images/products/radio-android-jbl.webp',
    features: [
      'Pantalla táctil HD 10 pulgadas',
      'Android Auto y Apple CarPlay',
      'GPS y mapas offline',
      'WiFi + Bluetooth 5.0',
      'Cámara de retroceso compatible',
      'Salida de audio 4 × 55W',
    ],
    compatible: ['Toyota Corolla', 'Hyundai Tucson', 'Kia Sportage', 'Chevrolet Sail', 'Nissan Sentra'],
    badge: 'Más vendido',
  },
  {
    id: 'radio-android-pioneer-9',
    name: 'Radio Android Pioneer 9"',
    brand: 'Pioneer',
    category: 'Car Audio',
    subcategory: 'Radios',
    code: 'ANT-CA-002',
    price: 159990,
    priceFormatted: '$159.990',
    description: 'Unidad multimedia Pioneer con pantalla de 9 pulgadas, sistema Android, conectividad total y sonido premium. Instalación limpia con adaptador de fábrica.',
    image: '/images/products/radio-pioneer.webp',
    features: [
      'Pantalla táctil 9 pulgadas',
      'Android nativo con Play Store',
      'Bluetooth multiconexión',
      'Ecualizador digital de 10 bandas',
      'Salida de video trasera',
      'Control desde volante compatible',
    ],
    compatible: ['Nissan March', 'Suzuki Swift', 'Kia Rio', 'Hyundai i10', 'Volkswagen Polo'],
  },

  // ── CAR AUDIO — PARLANTES ─────────────────────────────────────────────────
  {
    id: 'parlantes-jbl-65',
    name: 'Parlantes Coaxiales JBL 6.5"',
    brand: 'JBL',
    category: 'Car Audio',
    subcategory: 'Parlantes',
    code: 'ANT-CA-010',
    price: 89990,
    priceFormatted: '$89.990',
    description: 'Par de parlantes coaxiales JBL de 6.5 pulgadas con tweeter integrado. Potencia de 180W máximo, respuesta de frecuencia amplia y cono de polipropileno.',
    image: '/images/products/parlantes-jbl.webp',
    features: [
      'Par de parlantes 6.5"',
      'Potencia máx. 180W por par',
      'Tweeter de cúpula integrado',
      'Cono de polipropileno resistente',
      'Instalación directa plug & play',
    ],
    compatible: ['Universal — compatible con todos los modelos'],
  },
  {
    id: 'parlantes-pioneer-6x9',
    name: 'Parlantes Pioneer 6x9"',
    brand: 'Pioneer',
    category: 'Car Audio',
    subcategory: 'Parlantes',
    code: 'ANT-CA-011',
    price: 79990,
    priceFormatted: '$79.990',
    description: 'Par de parlantes triaxiales Pioneer de 6x9 pulgadas. Alta fidelidad, graves profundos y altos cristalinos para completar cualquier sistema de audio.',
    image: '/images/products/parlantes-pioneer.webp',
    features: [
      'Par de parlantes 6x9"',
      'Sistema triaxial 3 vías',
      'Potencia máx. 350W por par',
      'Respuesta de frecuencia 35Hz–25kHz',
    ],
    compatible: ['Universal'],
  },

  // ── CAR AUDIO — SUBWOOFER ─────────────────────────────────────────────────
  {
    id: 'subwoofer-pioneer-12',
    name: 'Subwoofer Pioneer 12"',
    brand: 'Pioneer',
    category: 'Car Audio',
    subcategory: 'Subwoofer',
    code: 'ANT-CA-020',
    price: 129990,
    priceFormatted: '$129.990',
    description: 'Subwoofer de 12 pulgadas Pioneer con bobina de voz de alta excursión. Graves profundos y precisos, ideal para completar cualquier sistema de audio.',
    image: '/images/products/subwoofer-pioneer.webp',
    features: [
      'Diámetro 12 pulgadas',
      'Potencia máx. 1200W',
      'Bobina de voz 4 ohm',
      'Cono de fibra de vidrio',
      'Compatible con amplificadores mono',
    ],
    compatible: ['Universal'],
    badge: 'Stock limitado',
  },
  {
    id: 'subwoofer-jbl-10',
    name: 'Subwoofer JBL 10"',
    brand: 'JBL',
    category: 'Car Audio',
    subcategory: 'Subwoofer',
    code: 'ANT-CA-021',
    price: 99990,
    priceFormatted: '$99.990',
    description: 'Subwoofer JBL de 10 pulgadas, ideal para instalaciones en cajones pequeños o medianos. Alta eficiencia y graves limpios para cualquier tipo de música.',
    image: '/images/products/subwoofer-jbl.webp',
    features: [
      'Diámetro 10 pulgadas',
      'Potencia máx. 800W',
      'Bobina de voz dual 2+2 ohm',
      'Diseño sellado o reflex',
    ],
    compatible: ['Universal'],
  },

  // ── SEGURIDAD — ALARMAS ───────────────────────────────────────────────────
  {
    id: 'alarma-hawk-homologada',
    name: 'Alarma Hawk Homologada',
    brand: 'Hawk',
    category: 'Seguridad',
    subcategory: 'Alarmas',
    code: 'ANT-SEG-001',
    price: 79990,
    priceFormatted: '$79.990',
    description: 'Alarma vehicular Hawk homologada ante el Ministerio de Transporte. Sensor de movimiento, control remoto de dos vías y sirena 120dB.',
    image: '/images/products/alarma-hawk.webp',
    features: [
      'Homologada — certificado incluido',
      'Control remoto de dos vías LCD',
      'Sirena 120dB',
      'Sensor de movimiento y golpe',
      'Inmovilizador electrónico',
      'Arranque por control remoto opcional',
    ],
    compatible: ['Compatible con todos los modelos'],
    badge: 'Certificado legal',
  },
  {
    id: 'gps-rastreador-brm',
    name: 'GPS Rastreador BRM Premium',
    brand: 'BRM',
    category: 'Seguridad',
    subcategory: 'GPS Rastreador',
    code: 'ANT-SEG-010',
    price: 109990,
    priceFormatted: '$109.990',
    description: 'GPS de rastreo en tiempo real con app de control para Android e iOS. Historial de recorridos, notificaciones push y corte de motor remoto.',
    image: '/images/products/gps-brm.webp',
    features: [
      'Rastreo GPS en tiempo real',
      'App de control para Android e iOS',
      'Notificaciones push al celular',
      'Corte de motor remoto',
      'Historial de recorridos',
      'Geocercas programables',
    ],
    compatible: ['Compatible con todos los modelos'],
    badge: 'Con GPS',
  },
  {
    id: 'sensores-reversa-hawk',
    name: 'Sensores de Reversa Hawk x4',
    brand: 'Hawk',
    category: 'Seguridad',
    subcategory: 'Sensores de Reversa',
    code: 'ANT-SEG-020',
    price: 49990,
    priceFormatted: '$49.990',
    description: 'Kit de 4 sensores de reversa ultrasónicos con alerta sonora. Instalación en parachoque trasero con display digital de distancia.',
    image: '/images/products/sensores-reversa.webp',
    features: [
      '4 sensores ultrasónicos',
      'Display digital de distancia',
      'Alerta sonora progresiva',
      'Rango de detección 0.3–2.5m',
      'Resistentes al agua',
    ],
    compatible: ['Universal — todos los vehículos'],
  },
  {
    id: 'cierre-centralizado-brm',
    name: 'Cierre Centralizado BRM 4P',
    brand: 'BRM',
    category: 'Seguridad',
    subcategory: 'Cierre Centralizado',
    code: 'ANT-SEG-030',
    price: 39990,
    priceFormatted: '$39.990',
    description: 'Kit de cierre centralizado para 4 puertas con control remoto. Instalación profesional incluida, compatible con alarmas Hawk y BRM.',
    image: '/images/products/cierre-centralizado.webp',
    features: [
      'Control 4 puertas simultáneo',
      'Control remoto incluido',
      'Compatible con alarmas BRM y Hawk',
      'Actuadores de alta resistencia',
    ],
    compatible: ['Universal'],
  },

  // ── POLARIZADO AMERICANO ──────────────────────────────────────────────────
  {
    id: 'polarizado-sedan-35',
    name: 'Polarizado Sedan 35%',
    brand: 'BRM',
    category: 'Polarizado Americano',
    subcategory: 'Polarizado Sedan',
    code: 'ANT-POL-001',
    price: 129990,
    priceFormatted: '$129.990',
    description: 'Lámina de polarizado americano al 35% para vehículos tipo sedan. Cumple ley chilena de polarizados. Certificado legal incluido con instalación.',
    image: '/images/products/polarizado-sedan.webp',
    features: [
      '35% transmisión de luz (cumple la ley)',
      'Certificado legal incluido',
      'Protección UV 99%',
      'Reducción de calor interior',
      'Anti-rayaduras en el exterior',
      'Garantía 3 años contra burbujas',
    ],
    compatible: ['Todos los sedán — medición previa incluida'],
    badge: 'Certificado legal',
  },
  {
    id: 'polarizado-suv-35',
    name: 'Polarizado SUV 35%',
    brand: 'BRM',
    category: 'Polarizado Americano',
    subcategory: 'Polarizado SUV',
    code: 'ANT-POL-002',
    price: 159990,
    priceFormatted: '$159.990',
    description: 'Polarizado americano al 35% para vehículos SUV y crossover. Mayor superficie cubierta, misma calidad de lámina y certificado legal incluido.',
    image: '/images/products/polarizado-suv.webp',
    features: [
      '35% transmisión de luz (cumple la ley)',
      'Certificado legal incluido',
      'Apto para SUV y crossover',
      'Protección UV 99%',
      'Garantía 3 años',
    ],
    compatible: ['Hyundai Tucson', 'Kia Sportage', 'Toyota RAV4', 'Nissan Qashqai'],
  },
  {
    id: 'polarizado-camioneta-35',
    name: 'Polarizado Camioneta 35%',
    brand: 'BRM',
    category: 'Polarizado Americano',
    subcategory: 'Polarizado Camionetas',
    code: 'ANT-POL-003',
    price: 149990,
    priceFormatted: '$149.990',
    description: 'Polarizado americano certificado para camionetas. Incluye ventanas de cabina y luneta trasera. Certificado legal por ventana aplicada.',
    image: '/images/products/polarizado-camioneta.webp',
    features: [
      'Lámina 35% certificada',
      'Incluye cabina completa',
      'Certificado legal por ventana',
      'Protección UV 99%',
    ],
    compatible: ['Toyota Hilux', 'Chevrolet D-Max', 'Mitsubishi L200', 'Ford Ranger'],
  },

  // ── ILUMINACIÓN LED ───────────────────────────────────────────────────────
  {
    id: 'turbo-led-h4',
    name: 'TURBO LED H4 6000K',
    brand: 'Genérica',
    category: 'Iluminación LED',
    subcategory: 'TURBO LED',
    code: 'ANT-LED-001',
    price: 39990,
    priceFormatted: '$39.990',
    description: 'Par de ampolletas TURBO LED H4 de alta potencia. Reemplazo directo de halógenos originales, 6000K luz blanca y 8000 lúmenes por par.',
    image: '/images/products/turbo-led-h4.webp',
    features: [
      'Par de ampolletas H4',
      '8000 lúmenes en total',
      '6000K — luz blanca diurna',
      'Plug & play sin modificar cableado',
      'Vida útil 30.000 horas',
    ],
    compatible: ['Modelos con casquillo H4 — consultar compatibilidad'],
  },
  {
    id: 'neblineros-led-h11',
    name: 'Neblineros LED H11',
    brand: 'Genérica',
    category: 'Iluminación LED',
    subcategory: 'Neblineros',
    code: 'ANT-LED-010',
    price: 29990,
    priceFormatted: '$29.990',
    description: 'Par de neblineros LED H11 para reemplazar las ampolletas originales del antiniebla. Alta visibilidad en condiciones de niebla, lluvia y polvo.',
    image: '/images/products/neblineros-h11.webp',
    features: [
      'Par de ampolletas H11',
      'Temperatura 6000K blanco puro',
      'Plug & play',
      'Resistentes al agua IP65',
    ],
    compatible: ['Consultar compatibilidad por modelo'],
  },

  // ── AIRE ACONDICIONADO ────────────────────────────────────────────────────
  {
    id: 'carga-ac-r134',
    name: 'Carga de A/C R134a',
    brand: 'Genérica',
    category: 'Aire Acondicionado',
    subcategory: 'Carga de A/C',
    code: 'ANT-AC-001',
    price: 39990,
    priceFormatted: '$39.990',
    description: 'Servicio de carga de gas refrigerante R134a para el sistema de aire acondicionado de tu vehículo. Incluye revisión de fugas y diagnóstico.',
    image: '/images/products/carga-ac.webp',
    features: [
      'Gas R134a certificado',
      'Diagnóstico previo incluido',
      'Revisión de fugas',
      'Prueba de funcionamiento',
    ],
    compatible: ['Todos los vehículos con A/C R134a'],
  },
  {
    id: 'filtro-polen',
    name: 'Filtro de Polen Habitáculo',
    brand: 'Genérica',
    category: 'Aire Acondicionado',
    subcategory: 'Filtro de Polen',
    code: 'ANT-AC-010',
    price: 19990,
    priceFormatted: '$19.990',
    description: 'Filtro de habitáculo antipolen de alta retención. Protege del polvo, alérgenos y contaminación del aire interior del vehículo.',
    image: '/images/products/filtro-polen.webp',
    features: [
      'Alta retención de partículas',
      'Bloquea alérgenos y polvo',
      'Mejora el flujo de aire',
      'Instalación incluida',
    ],
    compatible: ['Consultar compatibilidad por modelo'],
  },

  // ── INSUMOS ELÉCTRICOS ────────────────────────────────────────────────────
  {
    id: 'ampolletas-led-t10',
    name: 'Ampolletas LED T10 Interior',
    brand: 'Genérica',
    category: 'Insumos Eléctricos',
    subcategory: 'Ampolletas',
    code: 'ANT-INS-001',
    price: 4990,
    priceFormatted: '$4.990',
    description: 'Pack de ampolletas LED T10 para luces de cortesía, guanteras e iluminación interior. Reemplazo directo de las originales.',
    image: '/images/products/ampolletas-t10.webp',
    features: [
      'Pack x4 unidades',
      'Casquillo T10 estándar',
      'Color blanco 6000K',
      'Bajo consumo energético',
    ],
    compatible: ['Universal T10'],
  },

  // ── EQUIPAMIENTO ──────────────────────────────────────────────────────────
  {
    id: 'lona-maritima-camioneta',
    name: 'Lona Marítima Camioneta',
    brand: 'Genérica',
    category: 'Equipamiento',
    subcategory: 'Lonas Marítimas',
    code: 'ANT-EQ-001',
    price: 179990,
    priceFormatted: '$179.990',
    description: 'Lona marítima de alta resistencia para la caja de camioneta. Impermeable, resistente a rayos UV y con sistema de tensado fácil.',
    image: '/images/products/lona-maritima.webp',
    features: [
      'Lona de PVC marítimo 900g/m²',
      '100% impermeable',
      'Resistente a rayos UV',
      'Sistema de correas y hebillas',
      'Medida a pedido',
    ],
    compatible: ['Toyota Hilux', 'Chevrolet D-Max', 'Mitsubishi L200', 'Ford Ranger', 'Volkswagen Amarok'],
  },

  // ── LÁMINAS DE SEGURIDAD ──────────────────────────────────────────────────
  {
    id: 'lamina-seguridad-sedan',
    name: 'Lámina de Seguridad Sedan',
    brand: 'BRM',
    category: 'Láminas de Seguridad',
    subcategory: 'Láminas Sedan',
    code: 'ANT-LAM-001',
    price: 99990,
    priceFormatted: '$99.990',
    description: 'Lámina de seguridad para vidrios de sedan. Retiene los fragmentos de vidrio ante impactos, protegiendo a los ocupantes.',
    image: '/images/products/lamina-sedan.webp',
    features: [
      'Retención de fragmentos ante impacto',
      'Grosor 4mil (100 micrones)',
      'Protección UV 99%',
      'Transparente — no altera la visibilidad',
      'Certificado de instalación',
    ],
    compatible: ['Todos los modelos sedan'],
  },
  {
    id: 'lamina-seguridad-suv',
    name: 'Lámina de Seguridad SUV',
    brand: 'BRM',
    category: 'Láminas de Seguridad',
    subcategory: 'Láminas Camioneta SUV',
    code: 'ANT-LAM-002',
    price: 129990,
    priceFormatted: '$129.990',
    description: 'Lámina de seguridad para SUV y vehículos de mayor superficie. Alta resistencia a impactos, transparente y con protección UV.',
    image: '/images/products/lamina-suv.webp',
    features: [
      'Retención de fragmentos',
      'Apto para SUV y crossover',
      'Protección UV 99%',
      'Sin alterar visibilidad',
    ],
    compatible: ['Toyota RAV4', 'Hyundai Tucson', 'Kia Sportage', 'Nissan Qashqai'],
  },

  // ── VINILO ────────────────────────────────────────────────────────────────
  {
    id: 'vinilo-wrap-negro-mate',
    name: 'Vinilo Wrap Negro Mate',
    brand: 'Genérica',
    category: 'VINILO',
    subcategory: '',
    code: 'ANT-VIN-001',
    price: 325000,
    priceFormatted: '$325.000',
    description: 'Vinilo para empapelar vehículos completos o parciales. Negro mate premium, acabado de alta calidad con instalación profesional incluida.',
    image: '/images/products/vinilo-wrap.webp',
    features: [
      'Vinilo cast de alta durabilidad',
      'Negro mate premium',
      'Reversible — no daña la pintura',
      'Duración 5+ años con mantención',
      'Instalación profesional incluida',
    ],
    compatible: ['Todos los vehículos — cotización por modelo'],
    badge: 'Premium',
  },
];
